PREFIX mdb: <http://example.org/movieDB/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select ?movieURI ?title ?imdbLink ?plot where {

    bind(<http://example.org/movieDB/movie/%s> as ?movieURI)

    ?movieURI mdb:title ?title
    optional { ?movieURI rdf:about ?imdbLink}
    optional { ?movieURI mdb:plot ?plot}

} group by ?movieURI ?title ?imdbLink ?plot